'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4927
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Proyecto_Sena_Biblio_Sistem.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _32px_Crystal_Clear_action_loopnone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("32px-Crystal_Clear_action_loopnone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Avanzar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avanzar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property burn_badge_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("burn-badge_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Camara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Camara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CP_57_24x24_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CP 57_24x24-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Desktop_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desktop_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EDITAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDITAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ELIMINAR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELIMINAR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Floppy_24x24_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floppy_24x24-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_095_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder 095_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoRecoger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoRecoger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lazul1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lazul1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property libros_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("libros image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGO_FINAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO FINAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGO_FINAL_BIBLIIO_SISTEM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO FINAL BIBLIIO-SISTEM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo_Template___Logo_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo Template - Logo_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nueva_imagen__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nueva imagen (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nueva_imagen__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nueva imagen (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nueva_imagen__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nueva imagen (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Photoshop2_24x24_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Photoshop2_24x24-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Photoshop2_48x48_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Photoshop2_48x48-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s0307_life() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s0307-life", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sign_07_24x24_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sign 07_24x24-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sign_16_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sign 16_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Siguiente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Siguiente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_título() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin título", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_08_24x24_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 08_24x24-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
